Repository kryoniteorg/kryo-messaging, pull requests merged in 2021-09, with the labels that each got.

#2 Initial project setup
  .github/dependabot.yml
  .gitignore
  README.md
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  jitpack.yml
  settings.gradle.kts
Labels: enhancement

#4 Implemented basic MessagingService
  .github/dependabot.yml
  .github/workflows/docs.yaml
  .github/workflows/main.yaml
  README.md
  build.gradle.kts
  gradlew
  lombok.config
  src/main/java/org/kryonite/api/ActiveMqConnectionFactory.java
  src/main/java/org/kryonite/api/MessagingService.java
  src/main/java/org/kryonite/service/DefaultActiveMqConnectionFactory.java
  src/main/java/org/kryonite/service/DefaultMessagingService.java
  src/main/java/org/kryonite/service/message/Message.java
  src/main/java/org/kryonite/service/message/MessageCallback.java
  src/main/java/org/kryonite/service/message/PublishMessageTask.java
  src/main/java/org/kryonite/util/CustomObjectMapper.java
  src/main/java/org/kryonite/util/CustomTypeResolver.java
  src/test/java/org/kryonite/service/DefaultMessagingServiceTest.java
  src/test/java/org/kryonite/service/mock/MockActiveMqConnectionFactory.java
  src/test/java/org/kryonite/service/model/Animal.java
  src/test/java/org/kryonite/service/model/Person.java
Labels: enhancement

#7 fix folder naming for different docs versions
  .github/workflows/docs.yaml
Labels: bug

#8 Improve README
  README.md
Labels: documentation

#10 Replace mongojack with jackson
  README.md
  build.gradle.kts
Labels: bug

#12 Implement retry mechanism
  README.md
  build.gradle.kts
  src/main/java/org/kryonite/service/DefaultMessagingService.java
  src/main/java/org/kryonite/service/message/InternalMessage.java
  src/main/java/org/kryonite/service/message/PublishMessageTask.java
  src/test/java/org/kryonite/service/DefaultMessagingServiceTest.java
Labels: enhancement

#13 add sonarcloud integration
  .github/workflows/main.yaml
  build.gradle.kts
Labels: enhancement, github_actions

#18 Exclude Dependabot PRs from analysis
  .github/workflows/main.yaml
Labels: bug, github_actions

#19 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#14 Improve project base setup
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/main.yaml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: enhancement, github_actions

#15 Add jacoco coverage report
  .github/workflows/main.yaml
  build.gradle.kts
  src/main/java/org/kryonite/service/DefaultActiveMqConnectionFactory.java
  src/test/java/org/kryonite/service/DefaultActiveMqConnectionFactoryTest.java
Labels: enhancement

#20 Fix sonar recommendations
  build.gradle.kts
  src/main/java/org/kryonite/service/DefaultMessagingService.java
  src/main/java/org/kryonite/util/CustomObjectMapper.java
  src/test/java/org/kryonite/service/DefaultMessagingServiceTest.java
Labels: bug

#21 Bump version to 1.2.1
  build.gradle.kts
Labels: bug

#22 Multiple minor project setup improvements
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: bug, enhancement

#24 add security vulnerability contact
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#28 Rename projekt to kryo-messaging
  .github/workflows/main.yaml
  README.md
  build.gradle.kts
  lombok.config
  settings.gradle.kts
  src/main/java/org/kryonite/kryomessaging/api/ActiveMqConnectionFactory.java
  src/main/java/org/kryonite/kryomessaging/api/MessagingService.java
  src/main/java/org/kryonite/kryomessaging/service/DefaultActiveMqConnectionFactory.java
  src/main/java/org/kryonite/kryomessaging/service/DefaultMessagingService.java
  src/main/java/org/kryonite/kryomessaging/service/message/InternalMessage.java
  src/main/java/org/kryonite/kryomessaging/service/message/Message.java
  src/main/java/org/kryonite/kryomessaging/service/message/MessageCallback.java
  src/main/java/org/kryonite/kryomessaging/service/message/PublishMessageTask.java
  src/main/java/org/kryonite/kryomessaging/util/CustomObjectMapper.java
  src/main/java/org/kryonite/kryomessaging/util/CustomTypeResolver.java
  src/test/java/org/kryonite/kryomessaging/service/DefaultActiveMqConnectionFactoryTest.java
  src/test/java/org/kryonite/kryomessaging/service/DefaultMessagingServiceTest.java
  src/test/java/org/kryonite/kryomessaging/service/mock/MockActiveMqConnectionFactory.java
  src/test/java/org/kryonite/kryomessaging/service/model/Animal.java
  src/test/java/org/kryonite/kryomessaging/service/model/Person.java
  src/test/java/org/kryonite/kryomessaging/util/CustomObjectMapperTest.java
Labels: enhancement

#32 Remove redundant backticks in build.gradle.kts
  build.gradle.kts
Labels: bug
