Repository kryoniteorg/kryo-messaging, pull requests merged in 2022-01, with the labels that each got.

#65 Fix jitpack build with java 17
  README.md
  build.gradle.kts
  jitpack.yml
Labels: bug

#67 feat: Add scheduled label-sync workflow
  .github/workflows/label-sync.yaml
Labels: enhancement

#68 feat: Add possibility to dispatch label sync manually
  .github/workflows/label-sync.yaml
Labels: enhancement

#66 feat: Add release drafter action and config
  .github/release-drafter.yml
  .github/workflows/release-drafter.yaml
Labels: feature

#69 fix: Rename to KryoniteOrg to fit domain
  .github/workflows/docs.yaml
  .github/workflows/label-sync.yaml
  .github/workflows/main.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/wrapper-validation.yaml
  README.md
  build.gradle.kts
Labels: bugfix
